spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6543/sportclub}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:root}"

server:
  port: "${SERVER_PORT:8080}"

jwt.secret: "${JWT_SECRET}"