version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: sportclub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "6543:5432"

  backend:
    build: .
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sportclub
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: ",lAMNQl(SAy^)k]|S 6w7#dyZC#,c`&vSR(^7Z0*pAPGkGS-Bq-|5)>F*-hvI?ym"
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres